#!/bin/sh
# PROVIDE: acmewww
# REQUIRE: NETWORKING
# KEYWORD: shutdown
. /etc/rc.subr
name=acmewww
rcvar=acmewww_enable
desc="ACME webroot http server (lego HTTP-01)"
command=/usr/local/bin/python3
command_args="-m http.server 8402 --bind 127.0.0.1 --directory /usr/local/www/lego"
pidfile=/var/run/acmewww.pid
start_cmd="/usr/sbin/daemon -p ${pidfile} -u _lego ${command} ${command_args}"
load_rc_config $name
run_rc_command "$1"
