global
    log /var/run/log len 8192 local0 info
    maxconn 4096
    pidfile /var/run/haproxy.pid
    daemon
    stats socket /var/run/haproxy.sock mode 600 level admin
    ssl-default-bind-options ssl-min-ver TLSv1.2

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option redispatch
    timeout connect 10s
    timeout client 300s
    timeout server 300s
    timeout http-request 30s

frontend fe_http
    bind :80
    acl acme path_beg /.well-known/acme-challenge/
    use_backend be_acme if acme
    redirect scheme https code 301 if !acme

frontend fe_https
    bind :443 ssl crt /usr/local/etc/haproxy/certs/1c-gate.timpul.ru.pem
    option forwardfor
    default_backend be_packet_ubuntu

backend be_acme
    server acme 127.0.0.1:8402

backend be_packet_ubuntu
    option httpchk GET /health
    http-check expect status 200
    server ubuntu 10.77.0.2:6021 check inter 5s fall 3 rise 2
